import { StyleSheet } from "react-native";
import { colors } from "./themes";

const styles = StyleSheet.create({
  // Base home styles
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.black,
  },
  content: {
    fontSize: 18,
    color: "blue",
  },
  button: {
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: colors.primary,
    borderRadius: 12,
    alignItems: "center",
  },
  buttonPressed: {
    backgroundColor: colors.primaryDark,
  },
  buttonText: {
    color: colors.offwhite,
    fontSize: 16,
    fontWeight: "bold",
  },
  loadingIcon: {
    color: colors.primary,
    fontSize: 42,
    fontWeight: "800",
    letterSpacing: 1,
  },
  startupOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9999,
    elevation: 9999,
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  startupAnimationStage: {
    width: "100%",
    height: 116,
    alignItems: "center",
    justifyContent: "center",
  },
  startupRoadLine: {
    position: "absolute",
    left: 40,
    right: 40,
    bottom: 26,
    height: 2,
    borderRadius: 1,
    backgroundColor: colors.gunmetal,
  },
  startupCar: {
    width: 96,
    height: 76,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOpacity: 0.36,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
  },
  startupWordmark: {
    marginTop: 6,
    color: colors.primary,
    fontSize: 36,
    fontWeight: "900",
  },

  // Header
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
    backgroundColor: colors.black,
    borderBottomWidth: 1,
    borderBottomColor: colors.gunmetal,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.primary,
  },

  // Notification bell + badge
  notifButton: {
    position: "relative",
    padding: 4,
  },
  badge: {
    position: "absolute",
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "crimson",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  badgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
  },

  // Overlay that fills everything *under* the header
  notifOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.6)", // dim behind card (optional)
    justifyContent: "flex-start",
    alignItems: "stretch",
  },

  // Card now fills the whole content area under the header
  notifOverlayCard: {
    flex: 1,
    width: "100%",
    maxWidth: "100%",
    backgroundColor: colors.black,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopWidth: 0,
    borderColor: colors.gunmetal,
  },

  // header row, list, buttons, etc stay the same
  notifOverlayHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  notifOverlayTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.primary,
  },
  notifOverlayClose: {
    fontSize: 20,
    color: colors.offwhite,
  },

  notifOverlayBodyCenter: {
    marginTop: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  notifOverlayBodyText: {
    marginTop: 8,
    color: colors.offwhite,
    fontSize: 14,
  },
  notifErrorText: {
    color: "crimson",
    fontSize: 14,
  },

  notifList: {
    marginTop: 8,
    gap: 10,
  },
  notifItemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.gunmetal,
  },
  notifItemText: {
    color: colors.offwhite,
    fontSize: 14,
    marginBottom: 2,
  },
  notifItemHighlight: {
    fontWeight: "700",
    color: colors.primary,
  },
  notifItemSub: {
    color: "#888",
    fontSize: 12,
  },

  notifButtonsRow: {
    marginLeft: 8,
    flexDirection: "column",
    gap: 4,
  },
  notifAcceptBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: "center",
  },
  notifAcceptText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  notifDeclineBtn: {
    borderWidth: 1,
    borderColor: colors.gunmetal,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: "center",
    backgroundColor: colors.black,
  },
  notifDeclineText: {
    color: colors.offwhite,
    fontSize: 12,
    fontWeight: "600",
  },
  /* ---------------------------
      HOME PAGE TABS
  ----------------------------*/

  homeBody: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  homeBodyCentered: {
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 0,
  },

  createPlaceholderContainer: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    backgroundColor: colors.black,
  },
  createPlaceholderTitle: {
    color: colors.primary,
    fontSize: 32,
    fontWeight: "800",
    marginBottom: 8,
  },
  createPlaceholderSubtitle: {
    color: colors.offwhite,
    fontSize: 16,
    textAlign: "center",
  },

  createPremiumScreen: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: colors.black,
  },
  createPremiumCard: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.charcoal,
    padding: 20,
  },
  createPremiumIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(225, 6, 0, 0.14)",
    marginBottom: 14,
  },
  createPremiumTitle: {
    color: colors.offwhite,
    fontSize: 24,
    fontWeight: "800",
  },
  createPremiumSubtitle: {
    color: colors.silver,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  createPremiumFeatureList: {
    gap: 12,
    marginTop: 18,
  },
  createPremiumFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  createPremiumFeatureText: {
    flex: 1,
    color: colors.offwhite,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  createPremiumButton: {
    marginTop: 20,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: "center",
    backgroundColor: colors.primary,
  },
  createPremiumButtonText: {
    color: colors.offwhite,
    fontSize: 15,
    fontWeight: "800",
  },
  createScreen: {
    flex: 1,
    backgroundColor: colors.black,
  },
  createScroll: {
    flex: 1,
    backgroundColor: colors.black,
  },
  createContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 34,
  },
  createHeader: {
    marginBottom: 14,
  },
  createTitle: {
    color: colors.offwhite,
    fontSize: 28,
    fontWeight: "900",
  },
  createSubtitle: {
    color: colors.silver,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  createFormCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.charcoal,
    padding: 14,
  },
  createTwoColumnRow: {
    flexDirection: "row",
    gap: 10,
  },
  createTwoColumnField: {
    flex: 1,
  },
  createSecondaryAction: {
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.steel,
    backgroundColor: colors.gunmetal,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  createSecondaryActionText: {
    color: colors.offwhite,
    fontWeight: "800",
  },
  createLocationResolvedText: {
    color: colors.success,
    fontSize: 12,
    fontWeight: "700",
    marginTop: -4,
    marginBottom: 12,
  },
  createCoverPicker: {
    minHeight: 146,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.black,
    overflow: "hidden",
    marginBottom: 12,
    position: "relative",
  },
  createCoverPickerFilled: {
    borderColor: colors.steel,
  },
  createCoverImagePreview: {
    width: "100%",
    height: 164,
    backgroundColor: colors.gunmetal,
  },
  createCoverPlaceholder: {
    minHeight: 146,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
  },
  createCoverPlaceholderText: {
    color: colors.offwhite,
    fontSize: 14,
    fontWeight: "900",
  },
  createCoverPlaceholderSubtext: {
    color: colors.silver,
    fontSize: 12,
    fontWeight: "700",
  },
  createCoverActionOverlay: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 10,
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: "rgba(0, 0, 0, 0.72)",
    paddingVertical: 9,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 7,
  },
  createCoverActionText: {
    color: colors.offwhite,
    fontSize: 13,
    fontWeight: "900",
  },
  createCoverRemoveButton: {
    alignSelf: "flex-start",
    marginTop: -4,
    marginBottom: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.steel,
    backgroundColor: colors.gunmetal,
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  createCoverRemoveText: {
    color: colors.offwhite,
    fontSize: 12,
    fontWeight: "800",
  },
  createDateTimeTrigger: {
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.black,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  createDateTimeTriggerIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(225, 6, 0, 0.12)",
  },
  createDateTimeTriggerTextWrap: {
    flex: 1,
  },
  createDateTimeTriggerTitle: {
    color: colors.offwhite,
    fontSize: 14,
    fontWeight: "900",
  },
  createDateTimeTriggerSummary: {
    color: colors.silver,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  createDateTimeModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.72)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  createDateTimeModalCard: {
    width: "100%",
    maxWidth: 390,
    maxHeight: "88%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.black,
    padding: 12,
  },
  createDateTimeCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.black,
    padding: 10,
    marginBottom: 12,
  },
  createDateQuickRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingBottom: 9,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.gunmetal,
  },
  createDateQuickButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    backgroundColor: colors.charcoal,
    borderWidth: 1,
    borderColor: colors.gunmetal,
  },
  createDateQuickButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  createDateQuickButtonText: {
    color: colors.offwhite,
    fontSize: 12,
    fontWeight: "800",
  },
  createDateQuickButtonTextActive: {
    color: colors.black,
  },
  createCalendarHeader: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  createCalendarNavButton: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.charcoal,
    borderWidth: 1,
    borderColor: colors.gunmetal,
  },
  createCalendarMonthText: {
    color: colors.offwhite,
    fontSize: 14,
    fontWeight: "900",
  },
  createCalendarWeekRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  createCalendarWeekdayText: {
    flex: 1,
    textAlign: "center",
    color: colors.silver,
    fontSize: 11,
    fontWeight: "800",
  },
  createCalendarGrid: {
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.gunmetal,
  },
  createCalendarWeekDatesRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  createCalendarDaySlot: {
    flex: 1,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  createCalendarDayButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
    position: "relative",
  },
  createCalendarDayToday: {
    borderWidth: 1,
    borderColor: colors.steel,
  },
  createCalendarDaySelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  createCalendarDayText: {
    color: colors.offwhite,
    fontSize: 13,
    fontWeight: "800",
  },
  createCalendarDayTextMuted: {
    color: "#5f5f5f",
  },
  createCalendarDayTextSelected: {
    color: colors.black,
  },
  createCalendarTodayDot: {
    position: "absolute",
    bottom: 4,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.primary,
  },
  createCalendarTodayDotSelected: {
    backgroundColor: colors.black,
  },
  createTimeFieldGroup: {
    paddingTop: 8,
    gap: 8,
  },
  createTimeFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  createTimeFieldLabel: {
    color: colors.silver,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  createTimeField: {
    minWidth: 142,
    minHeight: 38,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.charcoal,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  createTimeFieldText: {
    color: colors.offwhite,
    fontSize: 13,
    fontWeight: "800",
  },
  createTimeDropdownGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    paddingVertical: 2,
  },
  createTimeDropdownOption: {
    width: "31.8%",
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    backgroundColor: colors.charcoal,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  createTimeDropdownOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  createTimeDropdownOptionText: {
    color: colors.offwhite,
    fontSize: 11,
    fontWeight: "800",
  },
  createTimeDropdownOptionTextSelected: {
    color: colors.black,
  },
  createDateTimeActionsRow: {
    marginTop: 10,
    alignItems: "flex-end",
  },
  createDateTimeDoneButton: {
    minWidth: 88,
    borderRadius: 9,
    backgroundColor: colors.primary,
    paddingVertical: 9,
    paddingHorizontal: 15,
    alignItems: "center",
  },
  createDateTimeDoneText: {
    color: colors.black,
    fontSize: 13,
    fontWeight: "900",
  },
  createDescriptionInput: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  createVisibilityToggle: {
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.steel,
    backgroundColor: colors.gunmetal,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  createVisibilityToggleActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  createVisibilityToggleText: {
    color: colors.offwhite,
    fontWeight: "800",
  },
  createVisibilityToggleTextActive: {
    color: colors.black,
  },
  createSubmitButton: {
    marginTop: 8,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: colors.primary,
  },
  createSubmitButtonText: {
    color: colors.offwhite,
    fontSize: 16,
    fontWeight: "900",
  },

  // Top tab row
  homeTabsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 16,
    gap: 12,
  },

  homeTabButton: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 20,
    backgroundColor: colors.gunmetal, // inactive state
  },
  homeTabButtonActive: {
    backgroundColor: colors.primary,
  },

  homeTabButtonText: {
    color: "#ccc",
    fontSize: 16,
    fontWeight: "600",
  },
  homeTabButtonTextActive: {
    color: colors.black, // visible on primary background
  },

  // Tab content wrapper
  homeTabContent: {
    marginTop: 6,
    padding: 12,
    flex: 1,
  },
  homeTabContentText: {
    color: colors.offwhite,
    fontSize: 16,
  },
  friendsPanel: {
    flex: 1,
  },
  meetsPanel: {
    flex: 1,
  },
  friendsHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  friendsHeaderTextWrap: {
    flexShrink: 1,
    minWidth: 180,
    paddingRight: 8,
  },
  friendsTitle: {
    color: colors.offwhite,
    fontSize: 22,
    fontWeight: "700",
  },
  friendsSubtitle: {
    color: colors.silver,
    fontSize: 14,
    marginTop: 4,
  },
  friendsRefreshButton: {
    backgroundColor: colors.gunmetal,
    borderWidth: 1,
    borderColor: colors.steel,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  friendsRefreshButtonPressed: {
    backgroundColor: colors.steel,
  },
  friendsRefreshButtonText: {
    color: colors.offwhite,
    fontSize: 14,
    fontWeight: "600",
  },
  meetHeaderActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  meetCreateButton: {
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.primaryDark,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  meetCreateButtonPressed: {
    opacity: 0.85,
  },
  meetCreateButtonText: {
    color: colors.black,
    fontSize: 14,
    fontWeight: "700",
  },
  meetsSearchWrap: {
    gap: 10,
    marginBottom: 14,
  },
  meetsFilterChipRow: {
    gap: 8,
    paddingRight: 6,
  },
  meetsClearFiltersButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.gunmetal,
    borderWidth: 1,
    borderColor: colors.steel,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  friendsList: {
    gap: 12,
    paddingBottom: 20,
  },
  friendCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.charcoal,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    borderRadius: 18,
    padding: 14,
    gap: 14,
  },
  friendCardPressed: {
    borderColor: colors.primary,
    transform: [{ scale: 0.99 }],
  },
  friendAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.gunmetal,
  },
  friendAvatarFallback: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primaryDark,
    alignItems: "center",
    justifyContent: "center",
  },
  friendAvatarFallbackText: {
    color: colors.offwhite,
    fontSize: 22,
    fontWeight: "700",
  },
  friendMeta: {
    flex: 1,
    gap: 4,
  },
  friendName: {
    color: colors.offwhite,
    fontSize: 18,
    fontWeight: "700",
  },
  friendHandle: {
    color: colors.primaryLight,
    fontSize: 14,
  },
  friendVisibility: {
    color: colors.silver,
    fontSize: 13,
  },
  friendRemoveButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.steel,
    backgroundColor: colors.gunmetal,
  },
  friendRemoveButtonPressed: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primary,
  },
  friendRemoveButtonDisabled: {
    opacity: 0.6,
  },
  friendRemoveButtonText: {
    color: colors.offwhite,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 20,
  },
  friendModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.72)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  friendModalCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: colors.charcoal,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    padding: 20,
    gap: 14,
  },
  friendModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  friendModalAvatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.gunmetal,
  },
  friendModalAvatarFallback: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryDark,
    alignItems: "center",
    justifyContent: "center",
  },
  friendModalAvatarFallbackText: {
    color: colors.offwhite,
    fontSize: 30,
    fontWeight: "700",
  },
  friendModalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.gunmetal,
    borderWidth: 1,
    borderColor: colors.steel,
  },
  friendModalCloseButtonPressed: {
    backgroundColor: colors.steel,
  },
  friendModalCloseButtonText: {
    color: colors.offwhite,
    fontSize: 18,
    fontWeight: "700",
  },
  friendModalName: {
    color: colors.offwhite,
    fontSize: 24,
    fontWeight: "700",
  },
  friendModalHandle: {
    color: colors.primaryLight,
    fontSize: 16,
  },
  friendModalInfoGroup: {
    gap: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: colors.black,
    borderWidth: 1,
    borderColor: colors.gunmetal,
  },
  friendModalLabel: {
    color: colors.silver,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  friendModalValue: {
    color: colors.offwhite,
    fontSize: 16,
    fontWeight: "600",
  },
  friendModalHint: {
    color: colors.silver,
    fontSize: 13,
    lineHeight: 19,
  },
  createMeetModalCard: {
    width: "100%",
    maxWidth: 420,
    maxHeight: "86%",
    backgroundColor: colors.charcoal,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  createMeetModalScroll: {
    width: "100%",
  },
  createMeetModalContent: {
    paddingBottom: 8,
  },
  createMeetModalTitle: {
    color: colors.offwhite,
    fontSize: 22,
    fontWeight: "700",
  },
  createMeetModalSubtitle: {
    color: colors.silver,
    fontSize: 14,
    marginTop: 4,
    marginBottom: 12,
  },
  createMeetFieldLabel: {
    color: colors.silver,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  createMeetChipRow: {
    gap: 8,
    paddingBottom: 10,
    paddingRight: 8,
  },
  createMeetChip: {
    borderWidth: 1,
    borderColor: colors.steel,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.gunmetal,
  },
  createMeetChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primaryDark,
  },
  createMeetChipPressed: {
    opacity: 0.8,
  },
  createMeetChipText: {
    color: colors.offwhite,
    fontSize: 13,
    fontWeight: "600",
  },
  createMeetChipTextSelected: {
    color: colors.black,
    fontWeight: "700",
  },
  createMeetMap: {
    height: 180,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.gunmetal,
    marginBottom: 8,
  },
  createMeetMapHint: {
    color: colors.silver,
    fontSize: 12,
    marginBottom: 12,
  },
  createMeetDescriptionInput: {
    minHeight: 88,
  },
  createMeetActionsRow: {
    marginTop: 8,
    flexDirection: "row",
    gap: 10,
  },
  createMeetActionButton: {
    marginTop: 0,
    flex: 1,
  },
  friendsEmptyState: {
    flex: 1,
    minHeight: 220,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
  },
  friendsEmptyTitle: {
    color: colors.offwhite,
    fontSize: 20,
    fontWeight: "700",
  },
  meetCard: {
    backgroundColor: colors.charcoal,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  meetCoverImage: {
    width: "100%",
    height: 150,
    borderRadius: 12,
    backgroundColor: colors.gunmetal,
  },
  meetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  meetTitle: {
    color: colors.offwhite,
    fontSize: 18,
    fontWeight: "700",
    flex: 1,
  },
  meetStatus: {
    color: colors.primaryLight,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  meetTimeText: {
    color: colors.offwhite,
    fontSize: 14,
    fontWeight: "600",
  },
  meetLocationText: {
    color: colors.silver,
    fontSize: 14,
  },
  meetDescription: {
    color: colors.silver,
    fontSize: 13,
    lineHeight: 18,
  },
  meetMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  meetMetaText: {
    color: colors.silver,
    fontSize: 12,
    fontWeight: "600",
  },
  meetAttendanceText: {
    color: colors.primaryLight,
    fontSize: 12,
    fontWeight: "600",
  },
  meetAttendanceButtonsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  meetViewOnMapButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.primaryDark,
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
    marginTop: 2,
  },
  meetViewOnMapButtonPressed: {
    opacity: 0.8,
  },
  meetViewOnMapButtonText: {
    color: colors.offwhite,
    fontSize: 12,
    fontWeight: "700",
  },
  meetAttendanceButton: {
    borderWidth: 1,
    borderColor: colors.steel,
    backgroundColor: colors.gunmetal,
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  meetAttendanceButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryDark,
  },
  meetAttendanceButtonPressed: {
    opacity: 0.8,
  },
  meetAttendanceButtonText: {
    color: colors.offwhite,
    fontSize: 12,
    fontWeight: "700",
  },
  meetTagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  meetTagPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.gunmetal,
    borderWidth: 1,
    borderColor: colors.steel,
  },
  meetTagPillText: {
    color: colors.offwhite,
    fontSize: 12,
    fontWeight: "600",
  },

  /* ---------------------------
     LOGIN INPUTS (shared)
  ----------------------------*/
  homeAuthCard: {
    width: "90%",
    maxWidth: 420,
    backgroundColor: colors.charcoal,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  homeAuthTitle: {
    marginBottom: 12,
    fontSize: 18,
    fontWeight: "700",
    color: colors.offwhite,
  },
  homeInput: {
    backgroundColor: colors.black,
    color: colors.offwhite,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.gunmetal,
  },
  homeInputFocused: {
    borderColor: colors.primary,
  },
  homeErrorText: {
    color: colors.error,
    marginTop: 4,
    marginBottom: 4,
  },

  homeSecondaryBtn: {
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.steel,
    backgroundColor: colors.gunmetal,
  },
  homeSecondaryBtnText: {
    color: colors.offwhite,
    fontWeight: "600",
  },
  homeSecondaryBtnPressed: {
    opacity: 0.7,
  },

  authScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: colors.black,
  },
  authCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: colors.charcoal,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.gunmetal,
    padding: 20,
  },
  authTitle: {
    color: colors.primary,
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 8,
  },
  authSubtitle: {
    color: colors.silver,
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 18,
  },
  authModeRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  authModeButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
    backgroundColor: colors.gunmetal,
  },
  authModeButtonActive: {
    backgroundColor: colors.primary,
  },
  authModeText: {
    color: colors.silver,
    fontWeight: "700",
  },
  authModeTextActive: {
    color: colors.offwhite,
  },
  authInput: {
    backgroundColor: colors.black,
    color: colors.offwhite,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.gunmetal,
  },
  authError: {
    color: colors.error,
    marginBottom: 10,
  },
  authMessage: {
    color: colors.success,
    marginBottom: 10,
  },
  authSubmitButton: {
    marginTop: 4,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: colors.primary,
  },
  authSubmitText: {
    color: colors.offwhite,
    fontSize: 16,
    fontWeight: "800",
  },
  authSecondaryButton: {
    marginTop: 12,
    alignItems: "center",
    paddingVertical: 10,
  },
  authSecondaryText: {
    color: colors.silver,
    fontWeight: "600",
  },
});

export default styles;
