import { StyleSheet } from "react-native";
import { colors } from "./themes";

const mapStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.black,
  },
  text: { fontSize: 18 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },

  cardContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 78,
    alignItems: "center",
  },
  card: {
    width: "92%",
    maxWidth: 440,
    borderRadius: 16,
    padding: 14,
    backgroundColor: "rgba(6,6,6,0.97)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  publicProfileCard: {
    minHeight: 320,
    paddingBottom: 72,
  },
  publicProfileScroll: {
    marginTop: 10,
    flexGrow: 0,
  },
  publicProfileScrollContent: {
    paddingBottom: 12,
  },
  profileNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  premiumBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(239,68,68,0.2)",
    borderWidth: 1,
    borderColor: "#ef4444",
  },
  premiumBadgeText: {
    color: "#ef4444",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  profileBio: {
    color: "#ddd",
    fontSize: 13,
    lineHeight: 18,
  },
  socialRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  socialPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(239,68,68,0.2)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.7)",
  },
  socialPillText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  carsSection: {
    marginTop: 14,
    gap: 8,
  },
  carsTitle: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  carRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 6,
  },
  carPhoto: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: "#141414",
  },
  carPhotoFallback: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  carPhotoFallbackText: {
    fontSize: 10,
    color: "#aaa",
    textAlign: "center",
  },
  carNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  carName: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  primaryTag: {
    color: "#ef4444",
    fontSize: 11,
    fontWeight: "700",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#eee",
  },
  avatarFallback: {
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    fontSize: 20,
    fontWeight: "700",
    color: "#333",
  },
  userPinMarker: {
    width: 54,
    height: 64,
    alignItems: "center",
  },
  userPinAvatarRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    backgroundColor: "#111",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  userPinAvatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 24,
  },
  userPinAvatarFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#202020",
  },
  userPinAvatarInitials: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
  },
  userPinTail: {
    position: "absolute",
    top: 40,
    width: 0,
    height: 0,
    borderLeftWidth: 9,
    borderRightWidth: 9,
    borderTopWidth: 16,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    zIndex: 1,
  },
  clusterPinMarker: {
    width: 78,
    height: 50,
    alignItems: "center",
    overflow: "visible",
  },
  clusterPinMarkerOffsetAboveUser: {
    height: 106,
    paddingTop: 56,
  },
  clusterAvatarFan: {
    width: 72,
    height: 42,
    zIndex: 3,
    overflow: "visible",
  },
  clusterAvatarFanOffsetAboveUser: {
    transform: [{ translateY: -56 }],
  },
  clusterAvatarRing: {
    position: "absolute",
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    backgroundColor: "#111",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  clusterAvatarLeft: {
    left: 8,
    top: 7,
    transform: [{ rotate: "-15deg" }],
    zIndex: 1,
  },
  clusterAvatarCenter: {
    left: 23,
    top: 0,
    transform: [{ rotate: "4deg" }],
    zIndex: 3,
  },
  clusterAvatarRight: {
    right: 8,
    top: 8,
    transform: [{ rotate: "16deg" }],
    zIndex: 2,
  },
  clusterAvatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 16,
  },
  clusterAvatarFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#202020",
  },
  clusterAvatarInitials: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
  },
  clusterAvatarCountBadge: {
    position: "absolute",
    right: 2,
    top: -4,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 4,
    borderRadius: 10,
    backgroundColor: "#121212",
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
    elevation: 6,
  },
  clusterAvatarCountText: {
    color: colors.primary,
    fontWeight: "900",
    fontSize: 10,
  },
  cardName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
  },
  cardSub: {
    fontSize: 14,
    color: "#ccc",
  },
  cardSubSmall: {
    fontSize: 12,
    color: "#aaa",
  },
  closeBtn: {
    padding: 6,
    marginLeft: 8,
  },
  closeBtnText: {
    fontSize: 18,
    color: "#fff",
  },
  cardActions: {
    position: "absolute",
    right: 14,
    bottom: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  friendBtn: {
    backgroundColor: "#ef4444",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  friendBtnText: {
    color: "#fff",
    fontWeight: "600",
  },
  friendBtnDisabled: {
    backgroundColor: "rgba(239,68,68,0.45)",
  },
  friendBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.85)",
    backgroundColor: "rgba(239,68,68,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  friendBadgeText: {
    color: "#fff",
    fontWeight: "700",
  },

  errorText: {
    marginTop: 8,
    color: "crimson",
    fontSize: 13,
  },
  meetDescriptionText: {
    marginTop: 8,
    color: "#cfcfcf",
    fontSize: 13,
    lineHeight: 18,
  },
  getDirectionsBtn: {
    marginTop: 12,
    alignSelf: "flex-start",
    backgroundColor: "#ef4444",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  getDirectionsBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
  },
  meetTagsRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  meetTagPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  meetTagPillText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  meetMarkerWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  meetMarkerIcon: {
    fontSize: 38,
    lineHeight: 40,
    color: "#ef4444",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 3,
  },
  mapControlsContainer: {
    position: "absolute",
    right: 16,
    zIndex: 20,
    elevation: 20,
    gap: 10,
  },
  mapControlButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: "rgba(8,8,8,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 8,
  },
  mapControlButtonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.96 }],
  },
  mapControlButtonActive: {
    borderColor: "rgba(239,68,68,0.8)",
    backgroundColor: "rgba(28,8,8,0.96)",
  },
  mapControlButtonInactive: {
    borderColor: "rgba(255,255,255,0.1)",
  },
  mapControlMeetIconInactive: {
    color: "#8a8a8a",
    opacity: 0.48,
  },
  meetsSheetContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
  },
  meetsSheet: {
    backgroundColor: "rgba(8,8,8,0.98)",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 10,
    height: "100%",
  },
  meetsSheetHandleWrap: {
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 8,
  },
  meetsSheetHandle: {
    width: 44,
    height: 4,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  meetsSearchInput: {
    backgroundColor: "#121212",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    color: "#fff",
    paddingLeft: 14,
    paddingRight: 40,
    paddingVertical: 10,
    marginBottom: 8,
    fontSize: 14,
  },
  meetsSearchIconWrap: {
    position: "absolute",
    right: 22,
    top: 26,
  },
  meetsSearchIcon: {
    color: "#8a8a8a",
    fontSize: 16,
    fontWeight: "700",
  },
  meetsListScroll: {
    flexGrow: 0,
  },
  meetsListContent: {
    gap: 8,
    paddingBottom: 2,
  },
  meetRowCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  meetLeftColumn: {
    width: 64,
    alignItems: "center",
  },
  meetDateBlock: {
    alignItems: "center",
  },
  meetDateDay: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 30,
    lineHeight: 30,
  },
  meetDateMonth: {
    color: "#bcbcbc",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  meetDateTime: {
    marginTop: 6,
    color: "#d2d2d2",
    fontSize: 12,
    fontWeight: "600",
  },
  meetRightColumn: {
    flex: 1,
    paddingTop: 2,
  },
  meetRowTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 24,
  },
  meetRowMeta: {
    color: "#a9a9a9",
    fontSize: 14,
    marginTop: 4,
  },
  meetActionsRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  meetActionText: {
    color: "#d4d4d4",
    fontSize: 12,
    fontWeight: "600",
  },
  meetActionDot: {
    color: "rgba(255,255,255,0.32)",
    fontSize: 14,
  },
  meetRowStatusText: {
    marginTop: 6,
    color: "#ef4444",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
});

export default mapStyles;
